const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const loader=$('#loader');addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),700));
const btn=$('#menuBtn'),nav=$('#mobileNav');btn.onclick=()=>{nav.classList.toggle('open');btn.classList.toggle('active')};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');btn.classList.remove('active')});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>observer.observe(e));
const petals=$('#petals'),petalCount=innerWidth<700?8:15;for(let i=0;i<petalCount;i++){const p=document.createElement('span');p.className='petal';p.style.left=Math.random()*100+'%';p.style.setProperty('--fall',11+Math.random()*9+'s');p.style.setProperty('--sway',2.5+Math.random()*3.8+'s');p.style.setProperty('--delay',-Math.random()*18+'s');p.style.setProperty('--drift',-90+Math.random()*180+'px');petals.appendChild(p)}
$$('.tilt').forEach(card=>{if(!matchMedia('(pointer:fine)').matches)return;card.onmousemove=e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${y*-7}deg) translateY(-6px)`};card.onmouseleave=()=>card.style.transform=''});
const progress=$('#progress'),heroScene=$('#heroScene'),heroPhoto=$('.hero-photo'),heroCopy=$('#heroCopy'),stamp=$('#heroStamp'),cupcake=$('#scrollCupcake'),gallery=$('#gallery'),galleryTrack=$('#galleryTrack');let target=0,current=0;
function clamp(v,a,b){return Math.min(b,Math.max(a,v))}function lerp(a,b,t){return a+(b-a)*t}function ease(t){return t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2}
function onScroll(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?y/max*100:0)+'%';target=y}addEventListener('scroll',onScroll,{passive:true});onScroll();
function frame(){current=lerp(current,target,.09);const vh=innerHeight;const hp=clamp(current/(vh*1.15),0,1);heroScene.style.transform=`translate3d(0,${hp*70}px,0) scale(${1+hp*.025})`;heroPhoto.style.transform=`scale(${1.05+hp*.035})`;heroCopy.style.transform=`translate3d(0,${hp*-45}px,0)`;heroCopy.style.opacity=1-hp*.72;stamp.style.transform=`translate3d(0,${hp*45}px,0) rotate(${8+hp*22}deg) scale(${1-hp*.18})`;
  const start=vh*.18,end=Math.max(vh*3.7,document.querySelector('#process').offsetTop+vh*.25);const p=clamp((current-start)/(end-start),0,1),e=ease(p);const mobile=innerWidth<720;const x0=mobile?72:78,x1=mobile?7:12;const wave=Math.sin(e*Math.PI*2.5)*(mobile?6:11);const x=lerp(x0,x1,e)+wave;const y=lerp(mobile?72:67,mobile?18:20,e)+Math.sin(e*Math.PI*3)*(mobile?5:8);const scale=lerp(mobile?.63:.82,mobile?.48:.62,e);const rot=lerp(-8,320,e);cupcake.style.opacity=p<.03?clamp(p/.03,0,1):p>.94?clamp((1-p)/.06,0,1):1;cupcake.style.transform=`translate3d(${x}vw,${y}vh,0) rotate(${rot}deg) scale(${scale})`;cupcake.style.setProperty('--shadowScale',String(lerp(1,.55,e)));cupcake.style.setProperty('--shadowOpacity',String(lerp(.62,.25,e)));cupcake.style.setProperty('--shine',String(p>.33&&p<.55?1:0));
  const gr=gallery.getBoundingClientRect();if(gr.top<vh&&gr.bottom>0){const gp=clamp((vh-gr.top)/(vh+gr.height),0,1);const maxMove=Math.max(0,galleryTrack.scrollWidth-innerWidth+40);galleryTrack.style.transform=`translate3d(${-gp*maxMove}px,0,0)`}
  requestAnimationFrame(frame)}requestAnimationFrame(frame);
